ERROR - 2023-05-12 00:45:15 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\project4\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\project4\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'lc_monitoring', 3306, '', 0)
#1 C:\xampp\htdocs\project4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project4\app\Models\LoginModel.php(39): CodeIgniter\Database\BaseConnection->query('select * from s...')
#4 C:\xampp\htdocs\project4\app\Controllers\LoginController.php(70): App\Models\LoginModel->getSectionDetail('7')
#5 C:\xampp\htdocs\project4\system\CodeIgniter.php(934): App\Controllers\LoginController->course_section()
#6 C:\xampp\htdocs\project4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#7 C:\xampp\htdocs\project4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\project4\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\project4\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\project4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project4\app\Models\LoginModel.php(39): CodeIgniter\Database\BaseConnection->query('select * from s...')
#3 C:\xampp\htdocs\project4\app\Controllers\LoginController.php(70): App\Models\LoginModel->getSectionDetail('7')
#4 C:\xampp\htdocs\project4\system\CodeIgniter.php(934): App\Controllers\LoginController->course_section()
#5 C:\xampp\htdocs\project4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#6 C:\xampp\htdocs\project4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\project4\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-05-12 00:45:15 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\LoginModel.php(39): CodeIgniter\Database\BaseConnection->query('select * from section where course_id=\'7\'')
 3 APPPATH\Controllers\LoginController.php(70): App\Models\LoginModel->getSectionDetail('7')
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\LoginController->course_section()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
